Sprint 2
SlTret/middle.messenger.praktikum.yandex pull request #2
Opened 2022-11-02 21:30 UTC by SlTret

2022-11-03 13:59 UTC, agadoev requested changes
Привет, @SlTret 
Спасибо за работу. Постарайся все svg иконки вынести в отдельные файлы. Так же я отметил места, которые, на мой взгляд, стоит исправить. Давай пофиксим это и двинемся дальше

2022-11-03 13:59 UTC, agadoev commented on package.json
>          "build": "parcel build src/index.html",
Нужно добавить скрипт для запуска eslint'a и stylelint'a. Зависимости есть, но они не используются

2022-11-03 13:59 UTC, agadoev commented on src/components/EventBus.ts
> +    _listeners: {[key: string]: Function[]};
Предлагаю задать более конкретный тип для подписчика
```suggestion
    _listeners: {[key: string]: ListenerFn[]};
```
где 
```type ListenerFn = (...args?: unknown) => void```

2022-11-03 13:59 UTC, agadoev commented on src/components/button/button.hbs
> +{{text}}
а где сама кнопка?

2022-11-03 13:59 UTC, agadoev commented on src/components/editTextField/editTextField.scss
> +}
Можно использовать вложенность, которую предоставляет scss
```suggestion
.user-info {
    width: 100%;
    height: 40px;
    background-color: $background-color;
    display: inline-flex;
    border: none;
    border-bottom: 0.1px solid $border-color;
    
    &__name {
    width: 50%;
    background-color: $background-color;
    display: flex;
    justify-content: flex-start;
    align-items: center;
}
}

```

2022-11-03 13:59 UTC, agadoev commented on src/pages/chat/chatPage.ts
> +                        console.log("href",href )
Отладочные console.log'и полезны при разработке, однако их лучше не держать в репозитории. Они загрязняют консоль и отвлекают внимание твоих коллег и тебя в будущем

2022-11-03 13:59 UTC, agadoev commented on src/pages/chat/chatPage.ts
> +                        const href = target.getAttribute("href");
Этот код выглядит странно. Тут у button'a считывается href, которого у button'a быть не должно. В href должна находиться ссылка, а не код ошибок (href - Hypertext Reference)

2022-11-03 13:59 UTC, agadoev commented on src/pages/registration/registrationPage.hbs
> +            {{!-- <button class="button" type="submit" href="chat">Зарегистрироваться</button>
Закомментированный код лучше не держать в репозитории. Он загрязняет кодовую базу и отвлекает внимание.

2022-11-03 13:59 UTC, agadoev commented on src/services/HttpTransport.ts
> +        acc + `${key}=${value}` + (index == arr.length - 1 ? "" : "&"), "?")
Выглядит довольно сложно, я бы сделал попроще

```
return "?" + Object
 .entries(data)
 .map(([key, value]) => `${key}=${value}`)
 .join("&")
```
добавляется еще один проход по объекту за O(n), но сильно на производительность это не повлияет

2022-11-03 13:59 UTC, agadoev commented on src/services/HttpTransport.ts
> +    request(url:string, options:{[key:string] : object | string} = {}, timeout = 5000) {
нужно сделать отдельный тип для options, сейчас выглядит трудночитаемо

2022-11-03 13:59 UTC, agadoev commented on src/services/RenderPage.ts
> +        if (!this.root)
тут нужно генерировать исключение, иначе мы не узнаем об ошибке

2022-11-03 13:59 UTC, agadoev commented on src/services/HttpTransport.ts
> +};
Лучше использовать union. Union не транспилируется в объект и нам не нужно дублировать код (сейчас для каждого свойства дублируется строка) + объект можно мутировать в рантайме

2022-11-03 13:59 UTC, agadoev commented on src/utils/patterns.ts
> +export const patterns = {
чтобы объект нельзя было изменить извне, можно использовать ```Object.freeze```

2022-11-03 23:01 UTC, SlTret commented on src/components/button/button.hbs
> +{{text}}
Название корневого тэга и его аттрибуты задаю в конструкторе компонента, чтобы не создавать лишний див.

2022-11-03 23:04 UTC, SlTret commented
Вроде поправил, svg - шки только не вынес

2022-11-04 23:01 UTC, agadoev commented on src/components/button/button.hbs
> +{{text}}
Для описания структуры DOM дерева есть язык HTML. Чтобы код был очевиднее и проще, лучше описывать структуру DOM'a именно в разметке, а не в JS коде. Так же, в JS коде проще допустить ошибку

2022-11-04 23:02 UTC, agadoev commented on src/components/editTextField/editTextField.scss
> +}
а вот эти классы почему не добавил как подклассы ```user-info```?

2022-11-04 23:03 UTC, agadoev commented on src/pages/registration/registrationPage.hbs
> +            {{!-- <button class="button" type="submit" href="chat">Зарегистрироваться</button>
комментарии не убраны

2022-11-04 23:04 UTC, agadoev commented on src/services/HttpTransport.ts
> +    return "?" + Object.entries(data).map(([key, value]) => `${key}=${value}`).join("&")
Перенеси каждый метод на новую строку, чтобы повысить читаемость

2022-11-04 23:04 UTC, agadoev commented on src/services/HttpTransport.ts
> +    data: object | null
еще важным свойством является ```headers: Record<string, string>```

2022-11-04 23:06 UTC, agadoev commented on src/services/HttpTransport.ts
> +            if (method === Method.GET || !data) {
Почему здесь до сих пор используется enum, если Methods уже является union'ом?

2022-11-04 23:08 UTC, agadoev approved these changes
Привет) 
Вроде поправил, но не все. Я оставил комментарии в тех местах, которые ты забыл подправить. Это мелочи, но их нужно доделать. В целом работа принимается
Удачи в следующем спринте

2022-11-25 22:46 UTC, merged